# .readthedocs.yaml
version: 2

# Build configuration for Read the Docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"   # Match your project’s Python version

sphinx:
  configuration: docs/conf.py   # Path to your Sphinx conf.py

# Optionally build PDF & ePub
formats:
  - pdf
  - epub

# Install your package and dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
